version: '3.9'
services:
  db:
    image: 'mysql:8.0'
    restart: always
    container_name: mysql
    build: 
      context: ./db
      dockerfile: Dockerfile
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: rinkudb
      MYSQL_ROOT_PASSWORD: qaz123!
    ports:
      - 3306:3306
    expose:
      - 3306
    #volumes:
    #  - './mysql:/var/lib/mysql'
    networks:
      - backend
  backend:
    depends_on: 
      - db
    image: node:erbium-alpine
    container_name: rinku-api
    restart: always
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - '2002:2002'
    expose:
      - 2002
    networks:
      - backend
      - frontend
  frontend:
    depends_on: 
      - backend
    image: nginx:1.17.1-alpine
    container_name: rinku-app
    restart: always
    build:
      context: ./rinku-app
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - frontend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
