version: '3.8'
services:
  db: 
    image: mysql:8.0
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: rinkudb
      MYSQL_ROOT_PASSWORD: qaz123!
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      